export const INITIAL_CATEGORIES = [
  {
    id: 'cat-coffee',
    name: 'Specialty Coffee Beans',
    slug: 'coffee-beans',
    icon: 'Coffee',
    description: 'Single origins, Chikmagalur estate beans, and house espresso blends',
  },
  {
    id: 'cat-dairy',
    name: 'Dairy & Alternative Milks',
    slug: 'dairy-milks',
    icon: 'Milk',
    description: 'Fresh cow milk, oat milk, almond milk, and barista blends',
  },
  {
    id: 'cat-syrups',
    name: 'Syrups & Gourmet Sauces',
    slug: 'syrups-sauces',
    icon: 'Sparkles',
    description: 'Artisan syrups, Belgian mocha sauce, caramel drizzle, and purées',
  },
  {
    id: 'cat-bakery',
    name: 'Bakery & Fresh Pastries',
    slug: 'bakery-pastries',
    icon: 'Croissant',
    description: 'Butter croissants, muffins, tea cakes, and artisanal cookies',
  },
  {
    id: 'cat-tea',
    name: 'Tea & Matcha Infusions',
    slug: 'tea-matcha',
    icon: 'Leaf',
    description: 'Ceremonial Japanese matcha, Darjeeling orthodox, and Assam chai blends',
  },
  {
    id: 'cat-packaging',
    name: 'Cups, Lids & Packaging',
    slug: 'cups-packaging',
    icon: 'Box',
    description: 'Ripple kraft hot cups, PLA iced cups, bagasse lids, and carry bags',
  },
  {
    id: 'cat-cleaning',
    name: 'Barista Cleaning & Tools',
    slug: 'barista-cleaning',
    icon: 'ShieldCheck',
    description: 'Grouphead detergents, milk wand cleaners, filters, and tamper accessories',
  },
];

export const INITIAL_INVENTORY_ITEMS = [
  {
    id: 'item-1',
    name: 'Chikmagalur Estate Arabica (Washed AAA)',
    categoryId: 'cat-coffee',
    sku: 'COF-CHK-101',
    quantity: 16,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 1450.00,
    reorderLevel: 5,
    parLevel: 30,
    supplier: 'Mercara Coffee Roasters',
    notes: 'Notes of milk chocolate & hazelnut. Signature pour-over bean.',
    vendorMappings: [
      {
        mappingId: 'vm-chk-01',
        vendorName: 'Mercara Coffee Roasters',
        vendorItemName: 'Chikmagalur AAA Washed Arabica (1kg)',
        vendorSku: 'MCR-CHK-AAA',
        unitPrice: 1450.00,
        isPreferred: true,
        leadTimeDays: 2,
        notes: 'Primary artisanal roastery partner',
      },
    ],
  },
  {
    id: 'item-2',
    name: 'Coorg Dark Roast Espresso Blend',
    categoryId: 'cat-coffee',
    sku: 'COF-CRG-102',
    quantity: 3,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 1150.00,
    reorderLevel: 8,
    parLevel: 25,
    supplier: 'Mercara Coffee Roasters',
    notes: 'House espresso base for lattes & cappuccinos. Reorder urgently.',
    vendorMappings: [
      {
        mappingId: 'vm-crg-01',
        vendorName: 'Mercara Coffee Roasters',
        vendorItemName: 'Monsoon Malabar Dark Roast Blend (1kg)',
        vendorSku: 'MCR-MMD-402',
        unitPrice: 1150.00,
        isPreferred: true,
        leadTimeDays: 2,
        notes: 'House signature espresso blend',
      },
    ],
  },
  {
    id: 'item-3',
    name: 'Single Origin Cold Brew Blend (1kg)',
    categoryId: 'cat-coffee',
    sku: 'COF-CLD-103',
    quantity: 10,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 1350.00,
    reorderLevel: 4,
    parLevel: 20,
    supplier: 'Mercara Coffee Roasters',
    notes: 'Coarse ground nitrogen-flushed single estate blend for 18-hour cold drip.',
    vendorMappings: [
      {
        mappingId: 'vm-cld-01',
        vendorName: 'Mercara Coffee Roasters',
        vendorItemName: 'Coorg Cold Brew Coarse Roast (1kg)',
        vendorSku: 'MCR-CLD-103',
        unitPrice: 1350.00,
        isPreferred: true,
        leadTimeDays: 2,
        notes: 'Coarse nitrogen-flushed packaging',
      },
    ],
  },
  {
    id: 'item-4',
    name: 'Monsooned Malabar AA (1kg Pouch)',
    categoryId: 'cat-coffee',
    sku: 'COF-MAL-104',
    quantity: 8,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 1550.00,
    reorderLevel: 4,
    parLevel: 18,
    supplier: 'Mercara Coffee Roasters',
    notes: 'Aged coastal beans with low acidity and thick chocolate crema.',
    vendorMappings: [
      {
        mappingId: 'vm-mal-01',
        vendorName: 'Mercara Coffee Roasters',
        vendorItemName: 'Aged Monsoon Malabar Special Reserve (1kg)',
        vendorSku: 'MCR-MAL-104',
        unitPrice: 1550.00,
        isPreferred: true,
        leadTimeDays: 2,
        notes: 'Monsooned micro-lot curing',
      },
    ],
  },
  {
    id: 'item-5',
    name: 'Decaf Swiss Water Process Arabica (1kg)',
    categoryId: 'cat-coffee',
    sku: 'COF-DEC-105',
    quantity: 4,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 1680.00,
    reorderLevel: 2,
    parLevel: 10,
    supplier: 'Mercara Coffee Roasters',
    notes: '100% chemical-free decaffeinated specialty Arabica.',
    vendorMappings: [
      {
        mappingId: 'vm-dec-01',
        vendorName: 'Mercara Coffee Roasters',
        vendorItemName: 'Swiss Water Decaf Washed Arabica (1kg)',
        vendorSku: 'MCR-DEC-105',
        unitPrice: 1680.00,
        isPreferred: true,
        leadTimeDays: 2,
        notes: 'Chemical-free Swiss water process',
      },
    ],
  },
];

export const INITIAL_PURCHASE_ORDERS = [
  {
    id: 'po-2026-001',
    poNumber: 'PO-2026-001',
    supplierName: 'Mercara Coffee Roasters',
    status: 'PENDING_DELIVERY',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    expectedDelivery: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
    items: [
      {
        itemId: 'item-2',
        itemName: 'Coorg Dark Roast Espresso Blend',
        sku: 'COF-CRG-102',
        orderedQty: 20.0,
        receivedQty: 0,
        unit: 'kg',
        unitPrice: 1150.00,
      },
      {
        itemId: 'item-1',
        itemName: 'Chikmagalur Estate Arabica (Washed AAA)',
        sku: 'COF-CHK-101',
        orderedQty: 15.0,
        receivedQty: 0,
        unit: 'kg',
        unitPrice: 1450.00,
      },
    ],
    totalEstimatedCost: 44750.00,
    notes: 'Weekly roastery replenishment for signature espresso bars.',
  },
  {
    id: 'po-2026-002',
    poNumber: 'PO-2026-002',
    supplierName: 'Mercara Coffee Roasters',
    status: 'DELIVERED',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    receivedBy: 'Store Lead (Operations)',
    items: [
      {
        itemId: 'item-1',
        itemName: 'Chikmagalur Estate Arabica (Washed AAA)',
        sku: 'COF-CHK-101',
        orderedQty: 10.0,
        receivedQty: 10.0,
        unit: 'kg',
        unitPrice: 1450.00,
      },
    ],
    totalCost: 14500.00,
    notes: 'Batch intake inspected and stored in climate controlled storage.',
  },
];

export const INITIAL_VENDORS = [
  {
    id: 'ven-mercara',
    name: 'Mercara Coffee Roasters',
    contactPerson: 'Wholesale Lead',
    email: 'b2b@mercararoasters.com',
    phone: '+91 98450 11223',
    city: 'Bengaluru, Karnataka',
    leadTimeDays: 2,
    paymentTerms: 'Net 15',
    notes: 'Primary artisanal roastery partner for specialty Arabica and Monsoon Malabar blends.',
  },
];

export const REGISTERED_CAFES = [
  {
    id: 'cafe-flagship',
    name: 'Specialty Artisan Café - Flagship',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: 'Flagship Store, Bengaluru, Karnataka',
    monthlyVolumeEstimate: '₹2,40,000 / mo',
    monthlyOrdersCount: 28,
    managerName: 'Store Lead',
    managerPhone: '+91 80 4123 4567',
    badge: 'Main Branch',
    activeDemands: [],
  },
];

export const INITIAL_STAFF_MEMBERS = [
  {
    id: 'staff-01',
    name: 'Store Admin',
    email: 'admin@cafepulse.io',
    phone: '+91 98450 12345',
    role: 'admin',
    roleLabel: 'Store Admin & General Manager',
    branch: 'Main Flagship Branch',
    shift: 'Full Day (Operations Lead)',
    status: 'ACTIVE',
    pin: '1234',
    joinedDate: '2025-06-15',
  },
  {
    id: 'staff-02',
    name: 'Inventory Manager',
    email: 'manager@cafepulse.io',
    phone: '+91 98450 55667',
    role: 'manager',
    roleLabel: 'Assistant Manager & Inventory Lead',
    branch: 'Main Flagship Branch',
    shift: 'Full Day (Operations Lead)',
    status: 'ACTIVE',
    pin: '9900',
    joinedDate: '2025-08-01',
  },
  {
    id: 'staff-03',
    name: 'Shift Lead Barista',
    email: 'headbarista@cafepulse.io',
    phone: '+91 97110 44332',
    role: 'head_barista',
    roleLabel: 'Head Barista & Shift Lead',
    branch: 'Main Flagship Branch',
    shift: 'Morning Shift (6:30 AM - 3:00 PM)',
    status: 'ACTIVE',
    pin: '5678',
    joinedDate: '2025-09-10',
  },
  {
    id: 'staff-04',
    name: 'Floor Barista',
    email: 'barista@cafepulse.io',
    phone: '+91 97110 88990',
    role: 'barista',
    roleLabel: 'Shift Barista (Floor POS)',
    branch: 'Main Flagship Branch',
    shift: 'Evening Shift (2:30 PM - 11:00 PM)',
    status: 'ACTIVE',
    pin: '1122',
    joinedDate: '2025-11-20',
  },
  {
    id: 'staff-05',
    name: 'Stock Auditor',
    email: 'auditor@cafepulse.io',
    phone: '+91 99220 33445',
    role: 'auditor',
    roleLabel: 'Inventory & COGS Auditor',
    branch: 'All Branches (Network)',
    shift: 'Flexible / On-Call',
    status: 'ACTIVE',
    pin: '4321',
    joinedDate: '2026-01-05',
  },
];
