export const DEMO_ACCOUNT = {
  uid: 'demo_cafepulse_admin',
  email: 'demo@cafepulse.io',
  password: 'demo',
  displayName: 'Aarav Sharma',
  cafeName: 'CaféPulse Flagship Roastery',
  branchName: 'Indiranagar Flagship Branch, Bengaluru',
  role: 'admin',
  roleLabel: 'Store Admin & General Manager',
  isStaff: false,
  isRoleLocked: false,
  pin: '1234',
};

export const INITIAL_CATEGORIES = [
  {
    id: 'cat-coffee',
    name: 'Specialty Coffee Beans',
    slug: 'coffee-beans',
    icon: 'Coffee',
    description: 'Single origins, estate beans, and house espresso blends',
  },
  {
    id: 'cat-dairy',
    name: 'Dairy & Alternative Milks',
    slug: 'dairy-milks',
    icon: 'Milk',
    description: 'Fresh milk, oat milk, almond milk, and barista editions',
  },
  {
    id: 'cat-syrups',
    name: 'Syrups & Gourmet Sauces',
    slug: 'syrups-sauces',
    icon: 'Sparkles',
    description: 'Artisan syrups, mocha sauce, caramel drizzle, and fruit purées',
  },
  {
    id: 'cat-bakery',
    name: 'Bakery & Fresh Pastries',
    slug: 'bakery-pastries',
    icon: 'Croissant',
    description: 'Butter croissants, muffins, cookies, and tea cakes',
  },
  {
    id: 'cat-tea',
    name: 'Tea & Matcha Infusions',
    slug: 'tea-matcha',
    icon: 'Leaf',
    description: 'Ceremonial matcha, green tea, orthodox teas, and chai blends',
  },
  {
    id: 'cat-packaging',
    name: 'Cups, Lids & Packaging',
    slug: 'cups-packaging',
    icon: 'Box',
    description: 'Hot cups, cold cups, lids, sleeves, and carry bags',
  },
  {
    id: 'cat-cleaning',
    name: 'Barista Cleaning & Tools',
    slug: 'barista-cleaning',
    icon: 'ShieldCheck',
    description: 'Grouphead detergents, milk wand cleaners, and bar accessories',
  },
];

export const INITIAL_INVENTORY_ITEMS = [
  {
    id: 'item-demo-01',
    name: 'Coorg Single-Estate Arabica Beans',
    categoryId: 'cat-coffee',
    sku: 'COORG-ARA-500',
    quantity: 18,
    unit: 'packs',
    packageWeight: 1.0,
    packageWeightUnit: 'kg',
    unitPrice: 620,
    reorderLevel: 5,
    parLevel: 25,
    supplier: 'Coorg Estate Roasters',
    notes: 'Medium-dark roast with chocolate and caramel tasting notes',
    vendorMappings: [
      {
        mappingId: 'vm-demo-01',
        vendorName: 'Coorg Estate Roasters',
        vendorItemName: 'Coorg Arabica 1kg Pack',
        vendorSku: 'COORG-ARA-500',
        unitPrice: 620,
        isPreferred: true,
        leadTimeDays: 2,
      },
    ],
  },
  {
    id: 'item-demo-02',
    name: 'Oatly Barista Edition Oat Milk',
    categoryId: 'cat-dairy',
    sku: 'OATLY-BAR-1L',
    quantity: 24,
    unit: 'litres',
    packageWeight: 1.0,
    packageWeightUnit: 'L',
    unitPrice: 280,
    reorderLevel: 8,
    parLevel: 36,
    supplier: 'Plant Harvest Dairy Co.',
    notes: 'Smooth micro-foam foaming oat milk for flat whites and lattes',
    vendorMappings: [
      {
        mappingId: 'vm-demo-02',
        vendorName: 'Plant Harvest Dairy Co.',
        vendorItemName: 'Oatly Barista 1L Carton',
        vendorSku: 'OATLY-BAR-1L',
        unitPrice: 280,
        isPreferred: true,
        leadTimeDays: 1,
      },
    ],
  },
  {
    id: 'item-demo-03',
    name: 'Madagascan Artisan Vanilla Syrup',
    categoryId: 'cat-syrups',
    sku: 'MONIN-VAN-750',
    quantity: 4,
    unit: 'bottles',
    packageWeight: 750,
    packageWeightUnit: 'ml',
    unitPrice: 540,
    reorderLevel: 5,
    parLevel: 12,
    supplier: 'Monin Gourmet Syrups India',
    notes: 'Pure bourbon vanilla extract syrup for specialty iced lattes (Low Stock Alert)',
    vendorMappings: [
      {
        mappingId: 'vm-demo-03',
        vendorName: 'Monin Gourmet Syrups India',
        vendorItemName: 'Monin Vanilla 750ml Glass Bottle',
        vendorSku: 'MONIN-VAN-750',
        unitPrice: 540,
        isPreferred: true,
        leadTimeDays: 3,
      },
    ],
  },
  {
    id: 'item-demo-04',
    name: 'Kyoto Ceremonial Uji Matcha',
    categoryId: 'cat-tea',
    sku: 'UJI-MAT-100',
    quantity: 8,
    unit: 'tins',
    packageWeight: 100,
    packageWeightUnit: 'g',
    unitPrice: 950,
    reorderLevel: 3,
    parLevel: 15,
    supplier: 'Kyoto Imports Direct',
    notes: 'First-harvest shade-grown ceremonial grade matcha from Uji, Kyoto',
    vendorMappings: [
      {
        mappingId: 'vm-demo-04',
        vendorName: 'Kyoto Imports Direct',
        vendorItemName: 'Uji Matcha 100g Vacuum Tin',
        vendorSku: 'UJI-MAT-100',
        unitPrice: 950,
        isPreferred: true,
        leadTimeDays: 5,
      },
    ],
  },
  {
    id: 'item-demo-05',
    name: 'French Butter Croissants (Fresh Bake)',
    categoryId: 'cat-bakery',
    sku: 'BAKE-CROIS-12',
    quantity: 14,
    unit: 'boxes',
    packageWeight: 12,
    packageWeightUnit: 'units',
    unitPrice: 420,
    reorderLevel: 4,
    parLevel: 20,
    supplier: 'Bakehouse Artisans Bengaluru',
    notes: 'Flaky 100% Normandy butter croissants baked fresh daily',
    vendorMappings: [
      {
        mappingId: 'vm-demo-05',
        vendorName: 'Bakehouse Artisans Bengaluru',
        vendorItemName: 'Butter Croissant 12-Box',
        vendorSku: 'BAKE-CROIS-12',
        unitPrice: 420,
        isPreferred: true,
        leadTimeDays: 1,
      },
    ],
  },
];

export const INITIAL_PURCHASE_ORDERS = [
  {
    id: 'po-demo-01',
    poNumber: 'PO-2026-001',
    supplierName: 'Coorg Estate Roasters',
    status: 'DELIVERED',
    totalEstimatedCost: 12400,
    totalCost: 12400,
    destinationCafe: 'Indiranagar Flagship Branch',
    receivedAt: '2026-08-25T10:30:00.000Z',
    receivedBy: 'Aarav Sharma (Store Admin)',
    items: [
      {
        itemId: 'item-demo-01',
        itemName: 'Coorg Single-Estate Arabica Beans',
        sku: 'COORG-ARA-500',
        orderedQty: 20,
        receivedQty: 20,
        unit: 'packs',
        unitPrice: 620,
      },
    ],
    notes: 'Monthly bulk green and roasted beans order',
    createdAt: '2026-08-24T08:00:00.000Z',
  },
  {
    id: 'po-demo-02',
    poNumber: 'PO-2026-002',
    supplierName: 'Plant Harvest Dairy Co.',
    status: 'PENDING_DELIVERY',
    totalEstimatedCost: 6720,
    totalCost: 6720,
    destinationCafe: 'Indiranagar Flagship Branch',
    items: [
      {
        itemId: 'item-demo-02',
        itemName: 'Oatly Barista Edition Oat Milk',
        sku: 'OATLY-BAR-1L',
        orderedQty: 24,
        receivedQty: 0,
        unit: 'litres',
        unitPrice: 280,
      },
    ],
    notes: 'Weekly barista alternative milk delivery',
    createdAt: '2026-08-26T09:15:00.000Z',
    expectedDelivery: '2026-08-28T14:00:00.000Z',
  },
];

export const INITIAL_VENDORS = [
  {
    id: 'ven-demo-01',
    name: 'Coorg Estate Roasters',
    contactPerson: 'Karthik Somanna',
    email: 'wholesale@coorgestate.in',
    phone: '+91 98450 11223',
    city: 'Madikeri, Coorg',
    category: 'Specialty Coffee Roaster',
    leadTimeDays: 2,
    paymentTerms: 'Net 30',
    notes: 'Direct farm-to-cup single origin shade-grown Arabica partner',
  },
  {
    id: 'ven-demo-02',
    name: 'Plant Harvest Dairy Co.',
    contactPerson: 'Meera Rao',
    email: 'orders@plantharvest.in',
    phone: '+91 99001 88776',
    city: 'Bengaluru, Karnataka',
    category: 'Alternative & Dairy Milks',
    leadTimeDays: 1,
    paymentTerms: 'Net 15',
    notes: 'Authorized regional distributor for Oatly Barista & fresh dairy',
  },
  {
    id: 'ven-demo-03',
    name: 'Monin Gourmet Syrups India',
    contactPerson: 'Vikram Joshi',
    email: 'b2b@moninindia.com',
    phone: '+91 80 4123 9900',
    city: 'Mumbai / Bengaluru',
    category: 'Syrups & Gourmet Sauces',
    leadTimeDays: 3,
    paymentTerms: 'Net 30',
    notes: 'Premium beverage flavoring and specialty café bar concentrates',
  },
];

export const REGISTERED_CAFES = [
  {
    id: 'demo_cafepulse_admin',
    uid: 'demo_cafepulse_admin',
    name: 'CaféPulse Flagship Roastery',
    branchName: 'Indiranagar Flagship Branch',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: '100ft Road, Indiranagar, Bengaluru, Karnataka',
    managerName: 'Aarav Sharma',
    managerPhone: '+91 80 4000 8000',
    badge: 'Flagship Lab',
    email: 'demo@cafepulse.io',
    registeredAt: '2026-08-01T09:00:00.000Z',
  },
];

export const INITIAL_STAFF_MEMBERS = [
  {
    id: 'staff-demo-01',
    name: 'Aarav Sharma',
    email: 'demo@cafepulse.io',
    role: 'admin',
    roleLabel: 'Store Admin & General Manager',
    branch: 'Indiranagar Flagship Branch',
    shift: 'General Operations',
    status: 'ACTIVE',
    pin: '1234',
    password: 'demo',
    userId: 'demo_cafepulse_admin',
  },
  {
    id: 'staff-demo-02',
    name: 'Priya Patel',
    email: 'priya.barista@cafepulse.io',
    role: 'head_barista',
    roleLabel: 'Head Barista (Shift Lead)',
    branch: 'Indiranagar Flagship Branch',
    shift: 'Morning Shift (6:30 AM - 3:00 PM)',
    status: 'ACTIVE',
    pin: '2024',
    password: 'staff',
    userId: 'demo_cafepulse_admin',
  },
  {
    id: 'staff-demo-03',
    name: 'Rohit Rao',
    email: 'rohit.floor@cafepulse.io',
    role: 'barista',
    roleLabel: 'Shift Barista (Floor POS)',
    branch: 'Indiranagar Flagship Branch',
    shift: 'Evening Shift (2:30 PM - 11:00 PM)',
    status: 'ACTIVE',
    pin: '4321',
    password: 'staff',
    userId: 'demo_cafepulse_admin',
  },
  {
    id: 'staff-demo-04',
    name: 'Ananya Nair',
    email: 'ananya.audit@cafepulse.io',
    role: 'auditor',
    roleLabel: 'Inventory & Stock Auditor',
    branch: 'Indiranagar Flagship Branch',
    shift: 'Weekly Audit Shift',
    status: 'ACTIVE',
    pin: '8888',
    password: 'staff',
    userId: 'demo_cafepulse_admin',
  },
];

